# Generated by Django 4.1.2 on 2022-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='like_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_users', to='Post.postmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
